### ISSUE TITLE
Dead code in INTERPRET-TOKEN

### ISSUE THREAD

**Issue by r13l** [robert-strandh/SICL#126]
I believe that https://github.com/robert-strandh/SICL/blob/master/Code/Reader/Simple/tokens.lisp#L157-L158 contains unreachable code: since the first IF already checked for the condition, the second IF’s condition can never be true.

**Comment by robert-strandh** [comment]
This entire directory contains dead code because it has been
replaced by Eclector which is in a separate repository and
which is separately maintained.
