### ISSUE TITLE
error in parse-pattern

### ISSUE THREAD

**Issue by kpoeck** [robert-strandh/SICL#127]
see
https://github.com/robert-strandh/SICL/blob/master/Code/Cleavir/Code-utilities/lambda-lists.lisp#L317
that must be 
```lisp
(error 'malformed-lambda-list-pattern :code nil)
````
instead of
```lisp
(error 'malformed-lambda-list-pattern)
````
otherwise the condition reporter errors while printing the condition in
https://github.com/robert-strandh/SICL/blob/master/Code/Cleavir/Code-utilities/condition-reporters-english.lisp#L294

Reproducible in clasp with
```lisp
(MACROLET ((%M (())
                   :GOOD))
        (%M NIL))
````
error in the lambda-list i signaled, but printing the condition errors

**Comment by robert-strandh** [comment]
Fixed, thanks!
