### ISSUE TITLE
cleavir-ir-visualizer Symbol instead of string in call to clim:draw-text*

### ISSUE THREAD

**Issue by kpoeck** [robert-strandh/SICL#128]
In https://github.com/robert-strandh/SICL/blob/master/Code/Cleavir/Intermediate-representation/Visualizer/gui.lisp#L96
I believe (node-label node) must be changed to (string (node-label node))

Without this change at least in clasp, just a symbol is passed to clim:draw-text* and errors later

**Comment by robert-strandh** [comment]
Fixed, thanks!
