### ISSUE TITLE
Where's Greatest Common Divisor?

### ISSUE THREAD

**Issue by veronikazaglotova** [robert-strandh/SICL#208]
Where's GCD defined, if it is at all? I lurk here to learn Common Lisp, loving it. Sorry for the disturbance

**Comment by robert-strandh** [comment]
We haven't defined that yet.  It is going to be a function that
calls BINARY-GCD, and BINARY-GCD will be a generic function.
Initially, there will be a method specialized only to FIXNUM and FIXNUM,
as the algorithms on bignums are complicated and we need to study them
more.

**Comment by veronikazaglotova** [comment]
Added in #209
