### ISSUE TITLE
Should get-dependencies.sh include Cyclosis

### ISSUE THREAD

**Issue by djuber** [robert-strandh/SICL#223]
When following the readme, after cloning SICL to ~/quicklisp/local-projects/,  running sh get-dependencies.sh, when I run the asdf:load-system successfully, and then `(boot)`, I received an error where component cyclosis-intrinsic was not found.

I found what I assume is the right repo (https://github.com/s-expressionists/Cyclosis), added that url to the DEPENDENCIES list in the script header, and re-ran, and was able to continue from the debugger successfully.

Should Cyclosis be downloaded automatically from the get-dependencies script like the other components, or is this a dependency that is expected to be loaded from quicklisp or already present? 

I assume this is related to (recent) changes at https://github.com/robert-strandh/SICL/commit/5eea8be84c2df65f1539fa2bb59ca1f25906def7 where cyclosis was added to the printer.

**Comment by no-defun-allowed** [comment]
It probably should - thanks for letting us know. I can't remember which libraries are on Quicklisp (if any), and I don't think Cyclosis is on Quicklisp, so one has to download Cyclosis manually.

Usually it would be best to get the most recent versions of the dependencies of SICL, nonetheless, and the Quicklisp release can be up to a month out of date.
