### ISSUE TITLE
LOOP: PUSH where PUSHNEW was likely intended

### ISSUE THREAD

**Issue by phoe** [robert-strandh/SICL#225]
https://github.com/robert-strandh/SICL/blob/1d2ba5433c23a6901211a0ffcd0641de940792b6/Code/Loop/for-as-clause.lisp#L60-L61

`add-for-as-subclause-parser` is used with symbols - I assume that `pushnew` is meant instead of `push` in there in order to avoid duplication of parsers and a minor memory leak.

**Comment by jgarte** [comment]
@phoe LOOP has been extracted, so now it's an issue for @yitzchak

**Comment by phoe** [comment]
OK, will close, check if it's still applicable, and move there.
