### ISSUE TITLE
Makefiles not working. Idk how Latex works, and would rather not learn it just to see documentation for this project. Please give us pdfs of all the papers, talks, and documentation for this project.

### ISSUE THREAD

**Issue by garare992** [robert-strandh/SICL#240]
Example of makefile not working:
https://github.com/robert-strandh/LispOS/issues/4

Reposting this open issue from 5 years ago:
https://github.com/robert-strandh/SICL/issues/134

**Comment by robert-strandh** [comment]
The PDFs are already available.  
http://metamodular.com/SICL/sicl-specification.pdf
http://metamodular.com/SICL/ for papers.
http://metamodular.com/closos.pdf for LispOS
