### ISSUE TITLE
Simple reader does not allow backquote after sharpsign-dot

### ISSUE THREAD

**Issue by ruricolist** [robert-strandh/SICL#26]
E.g., trying to read something like

```
#.`,t
```

Raises an `invalid-context-for-backquote` error.

I can't find anything about it in the spec, but at least Clozure, SBCL, CLISP, ECL, and Allegro all allow it.

**Comment by robert-strandh** [comment]
Thanks for pointing this out.  I think I fixed it.

Your remark also allowed me to introduce a new macro named
WITH-PRESERVED-BACKQUOTE-CONTEXT similar to the macro I used in the
Cleavir compiler for preserving top-level-ness of forms.
