### ISSUE TITLE
"language" misspelled in Code/Cleavir/Generate-AST/condition-reporters-english.lisp

### ISSUE THREAD

**Issue by wobh** [robert-strandh/SICL#41]
Casually reviewing this PR https://github.com/robert-strandh/SICL/commit/8f4370e97ba4297ed893d1a13d471fce82361550 and it looks like language is misspelled "langauge" throughout Code/Cleavir/Generate-AST/condition-reporters-english.lisp.

Update: also in the `*langauge*` parameter for Code/Conditions/conditions.lisp

**Comment by dkochmanski** [comment]
This issue should be closed (fixed in the repository, `*language*` typo fixed in #49)
