### ISSUE TITLE
Graphviz drawing fails if IR contains constant strings

### ISSUE THREAD

**Issue by Bike** [robert-strandh/SICL#43]
E.g., the compilation of (lambda () "foo") will result in DOT like the following

```
G813 [fillcolor = orange, label = "'"foo""]
```

Which cannot be compiled into an image: syntax error in line 12 near '"'

This line is produced by cleavir-ir-graphviz:draw-datum

```
(format stream "   ~a [fillcolor = orange, label = \"~s\"]~%"
        (datum-id datum) (form datum)))
```

This would be difficult to fix because l-t-v forms are arbitrary. Maybe some kind of hack with pprint dispatch?

though i haven't checked, i assume this affects other kinds of constant-ish inputs.

**Comment by dkochmanski** [comment]
won't replacing all `"` in `(format nil "~s" (form datum))` with `\"` work for that?

**Comment by Bike** [comment]
let's see... off the top of my head, if the lisp string is «\"fire\"», that transform would make it «\\"fire\\"», which i don't think would work.

**Comment by dkochmanski** [comment]
it will produce `[label = "«\"fire\"»"]` (and `dot` doesn't seem to blurp on this kind of thing)
```
(format stream "   ~a [fillcolor = orange, label = \"~s\"]~%"
        (datum-id datum) (fix-quotes (form datum))))
```

(see http://i.imgur.com/I8JMPmh.png)

**Comment by Bike** [comment]
«» were not meant to be characters in the string, and it looks like markdown kind of ate my escapes. I meant, start with backslash doublequote f i r e backslash doublequote, i.e. the lisp string has backslashes in it, not just quotation marks. You transform and get backslash backslash doublequote f i r e backslash backslash doublequote. The backslashes escape the backslashes and the doublequotes are unescaped.

**Comment by robert-strandh** [comment]
Graphviz drawing is no longer supported.  Clients who wish to use
this tool will have to maintain their own version.  IR visualization is now
done with a CLIM-based tool.
