### ISSUE TITLE
Improve error reporting in REMF

### ISSUE THREAD

**Issue by robert-strandh** [robert-strandh/SICL#81]
In Code/Cons/remf-defmacro.lisp, there is a comment that says 
"FIXME: Handle errors better".

The way error handling should be improved is:

* A specific condition should be created for the errors that are
signaled in this macro.  That specific error should be defined in
conditions.lisp, modeled after the other ones already in that file.
the condition should include the list that was given to REMF.

* An English-language condition reporter should be added to
condition-reporters-english.lisp in the same directory, also modeled
after the other reporters in that file.

* Existing calls to ERROR should be modified to take the name (a
symbol) of the new condition as its first argument, and the offending
list should be added as a keyword argument.

**Comment by areinisc** [comment]
I think I've done this, but I'm not sure the correct way to get the changes to you.  Do I push to a new remote under my username@github and then ... pull request?

**Comment by robert-strandh** [comment]
Pull request merged.  I fixed a minor indentation issue, and I took
advantage of the situation by untabifying that file, so as to avoid
GitHub rendering problems in the future.

Thank you so much for helping.
